# Generated by Django 2.1.7 on 2019-02-16 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.GenericIPAddressField(default='0.0.0.0')),
                ('port', models.PositiveIntegerField(default=8888, unique=True)),
                ('method', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('timeout', models.IntegerField(default=300)),
                ('fast_open', models.BooleanField(default=False)),
                ('workers', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'start'), ('stop', 'stop'), ('restart', 'restart'), ('status', 'status')], max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
