# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('passwd', models.CharField(default='1234', max_length=20)),
                ('encode', models.CharField(choices=[('aes-256-cfb', 'aes-256-cfb'), ('rc4-md5', 'rc4-md5'), ('chacha20', 'chacha20'), ('aes-256-gcm', 'aes-256-gcm'), ('camellia-256-cfb', 'camellia-256-cfb')], default='aes-256-cfb', max_length=25)),
            ],
        ),
    ]
